version: "3.8"

services:
  router:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 30
        delay: 2s
        window: 10s
    volumes:
      - certificates:/etc/certificates/:rw
      - fpm-socket:/fpm-socket/
      - ./etc/nginx/30-installer.sh:/docker-entrypoint.d/30-installer.sh:ro
      - ./etc/nginx/50-acmesh.sh:/docker-entrypoint.d/50-acmesh.sh:ro
      - ./etc/nginx/healthcheck.sh:/healthcheck.sh
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      CERTIFICATE_DOMAIN_NAMES: "example.com www.example.com"
    healthcheck:
      test: /bin/sh /healthcheck.sh
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      hostnet: {}

  application:
    image: grigori/phpextensions:7.4-fpm
    volumes:
      - fpm-socket:/fpm-socket/
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - type: bind
        source: ./scripts/
        target: /scripts/
        consistency: cached
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 20
        delay: 2s
        window: 10s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      backend: {}

  database:
    image: mysql:5.7
    volumes:
      - ./etc/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 20
        delay: 30s
        window: 120s
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    healthcheck:
      test: mysql -u$$MYSQL_USER --password=$$MYSQL_PASSWORD -e "quit" 2>/dev/null
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      backend: {}

volumes:
  certificates:
  db-data:
  fpm-socket:

networks:
  hostnet:
    external: true
    name: host
  backend:
    driver: bridge
    internal: true
