version: "3.7"

services:

  router:
    environment:
      LOCAL_DOMAIN_NAME: "example.localhost"
    volumes:
      - ./nginx/40-issue-selfsigned.sh:/docker-entrypoint.d/40-issue-selfsigned.sh:ro
    ports:
      - "80:80"
      - "443:443"

  database:
    ports:
      - "3306:3306"

networks:
  hostnet:
    external: false
    driver: bridge
    name: hostnet
  backend:
    internal: false
