version: "3.8"

services:

  router:
    environment:
      LOCAL_DEPLOYMENT: "1"
    deploy:
      restart_policy:
        condition: none
    healthcheck:
    ports:
      - "80:80"
      - "443:443"

networks:
  hostnet:
    external: false
    driver: bridge
    name: hostnet
