version: "3.8"

services:

  router:
    environment:
      SELF_SIGNED_ONLY: "1"
    deploy:
      restart_policy:
        condition: none
    healthcheck:
      retries: 0
    ports:
      - "80:80"
      - "443:443"

networks:
  hostnet:
    external: false
    driver: bridge
    name: hostnet
