version: "3.8"

services:
  router:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 300
        delay: 30s
        window: 20s
    volumes:
      # ACME account config and certificates
      - acme:/acme/:rw
      # background issuing and renewing ACME certificates
      - ./etc/50-acmesh.sh:/docker-entrypoint.d/50-acmesh.sh:ro
      - ./etc/healthcheck.sh:/healthcheck.sh
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    environment:
      CERTIFICATE_DOMAIN_NAMES: "example.com www.example.com"
      LOCAL_DOMAIN_NAME: "example.localhost"
      ACCOUNTEMAIL: "test@example.com"
    healthcheck:
      test: /bin/sh /healthcheck.sh
      interval: 2s
      timeout: 5s
      retries: 2
      start_period: 15s
    networks:
      hostnet: {}

volumes:
  acme:

networks:
  hostnet:
    external: true
    name: host
